### ISSUE TITLE
Pd crashes on patch opening

### ISSUE THREAD

**Issue by aronco206** [cuinjune/ofxOfelia#14]
The following patch, which utilizes ofImage, causes Pure Data to crash upon opening. There seems to be an issue when [loadbang] is sent to the message box containing the image name to be loaded. I'm running macOS 10.14.5, Pd-0.49-1, and ofelia 2.3.1.

I've attached the patch that causes the crash and one with a workaround. I've noticed that simply adding a [delay 1] object before the message box will fix the crash.

[ofCrash.zip](https://github.com/cuinjune/ofxOfelia/files/3336830/ofCrash.zip)

Sidenote:
This is an isolated version of a larger patch. In the larger patch, a number box would increase by 1 when receiving a particular MIDI command. This number box was connected to a variety of [select] objects increasing sequentially (like: [select 1] [select 2] [select 3] etc...). These [select] objects were connected to a variety of message boxes to load various images and were used to change which image ofelia displayed. Thus I was able to toggle through images by pressing a MIDI note. On patch load, a [loadbang] objects was set up to send a "1" and trigger the first image, which is how this problem started and I since isolated it.

**Comment by cuinjune** [comment]
Your patch crashes because it calls `ofImage:load()` function before the graphics window is created.
This is explained in `pd warnings` subpatch in ofelia's help file.

The safest rule is to always use [ofSetup] instead of [loadbang] to trigger ofelia objects on patch load. (except when creating a graphics window with [ofWindow] on startup)

[ofSetup] will output "bang" when the graphics window is created and it will also output "bang" when a patch is being opened while the graphics window already exists so you don't need to use [loadbang] and [delay] for ofelia objects and abstractions.

<img width="591" alt="Screen Shot 2019-06-28 at 11 17 14 AM" src="https://user-images.githubusercontent.com/24947986/60312446-4c8d8d00-9996-11e9-9d8a-3e198e8f382d.png">

**Comment by aronco206** [comment]
Thank you so much!
